name: Renode Automated Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    # Get the arm-non-eabi-gcc toolchain   
    - name: Install arm-none-eabi-gcc
      uses: fiam/arm-none-eabi-gcc@v1
      if: steps.cache-arm-gcc.outputs.cache-hit != 'true'
      with:
          # The arm-none-eabi-gcc release to use.
          release: '9-2019-q4' 

    - name: Build Firmware
      run: make -j4


    - name: Renode Tests
      run: ./docker-test.sh 

    - name: Upload Output Dir
      uses: actions/upload-artifact@v2
      with:
        name: Renode Robot Output Dir
        path: test_output/

    - name: Upload Report
      uses: actions/upload-artifact@v2
      with:
        name: Renode Robot Report
        path: test_output/report.html

    - name: Upload Log
      uses: actions/upload-artifact@v2
      with:
        name: Renode Robot Log
        path: test_output/log.html
