name: Renode Automated Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    # Get the arm-non-eabi-gcc toolchain   
    - name: Install arm-none-eabi-gcc
      uses: fiam/arm-none-eabi-gcc@v1
      with:
          # The arm-none-eabi-gcc release to use.
          release: '9-2019-q4' 

    - name: Build Firmware
      run: make -j4

    - name: Upload ELF
      uses: actions/upload-artifact@v2
      with:
        name: renode-example.elf
        path: build/renode-example.elf

    - name: Renode Tests
      run: ./docker-test.sh 

    - name: Upload Output Dir
      uses: actions/upload-artifact@v2
      with:
        name: Renode Test Results
        path: test_results/
